sudo: required
language: go
dist: bionic
cache:
  directories:
    - $GOPATH/pkg/dep
go:
  - "1.14"
services:
  - docker
jobs:
  include:
    - stage: build
      name: unit tests
      install: make install
      script: make test_unit
    - stage: build
      install: make install
      name: lint
      script: make lint
    - stage: build
      name: integration tests
      install: integ/install.sh
      before_script: integ/setup.sh
      script: "sudo -E \"PATH=$PATH\" integ/test.sh"
    - stage: release
      if: (branch = master AND type = push) OR tag IS present
      name: docker build and push
      install: true
      script: make dockerhub_push

after_success:
- bash < (curl -s https://codecov.io/bash)
