
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision = "6702109cc68eb6fe6350b83e14407c8d7309fd1a"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "0.0.7"

[[constraint]]
  name = "github.com/lyft/flytestdlib"
  source = "git@github.com:lyft/flytestdlib"
  version = "^0.1.0"
