# This is default configuration file.
# Real configuration when running inside K8s (local or otherwise) lives in a ConfigMap
# The operator will replace "job" field with the correct flink job name
# ingressUrlFormat: "{{$jobCluster}}.xyz.net"
operator:
  useKubectlProxy: true
  containerNameFormat: "%s-unknown"
  statemachineStalenessDuration: 2m
logger:
  show-source: true
  level: 5
